### ISSUE TITLE
Problem of products text translation on the list view

### ISSUE THREAD

**Issue by randieri** [jameskoster/woocommerce-grid-list-toggle#11]
Hi,
I use QTranslate-X for support my dual language website

When i switch from grid to list view on the products title text appears a bug as reported below:

Infrared Illuminators Compact Series INFRARED ILLUMINATORS COMPACT SERIES (6) [:it]Illuminatori ad Infrarosso Serie Compatta[:en]Infrared Illuminators Compact Series[:]

Normally by the Grid view it is working and the right text is reported below

INFRARED ILLUMINATORS COMPACT SERIES (6)

Please could you fix this bug?

This is the relative web page that gave me this bug:
http://www.intellisystem.it/en/product-category/products/video-surveillance/infrared-illuminators/

Thanks in advance 

Regards

Cristian Tandieri

**Comment by jameskoster** [comment]
The plugin uses a WooCommerce core function to get the product excerpt. That function essentially just calls `the_excerpt();` which is a core WordPress function. You'll need to speak to QTranslate about this, I don't think it's an issue in grid list toggle.
