### ISSUE TITLE
List view without images?

### ISSUE THREAD

**Issue by octoberzodiac** [jameskoster/woocommerce-grid-list-toggle#4]
Hi, I need a list view toggle option on my store page that lists my products without images and also allows displaying of other custom Woo attributes. Is this possible with your plugin? Are you able to help me accomplish this?

**Comment by jameskoster** [comment]
Hi,

Please post stuff like this on wordpress.org. It can be done, but will need some custom development beyond what the plugin offers by default.

Thanks
