### ISSUE TITLE
Adding the option to disable the inline css added by the plugin?

### ISSUE THREAD

**Issue by dingo-d** [jameskoster/woocommerce-grid-list-toggle#5]
Currently the inline styling of the plugin will make it impossible to override some styling because of the `!important` tag. 

It would be great if the option would be added to either disable the styling, or to modify it from within the wordpress more easily.

**Comment by jameskoster** [comment]
I assume you're referring to the list styles? Unfortunately, using `!important` there is the safest way to ensure the layout is applied. The easiest way to tweak this would be to enqueue your own CSS later than the plugin CSS and over rule from there.

Cheers
