### ISSUE TITLE
How can I display the gridlist-toggle in another hook ?

### ISSUE THREAD

**Issue by montalvomiguelo** [jameskoster/woocommerce-grid-list-toggle#7]
The method `gridlist_toggle_button()` that displays the component is hooked into `woocommerce_before_shop_loop ` action_hook... How could I unhook from there an hook into another action_hook for example `woocommerce_before_main_content` 

```php
<?php
global $WC_List_Grid;
remove_action( 'woocommerce_before_shop_loop', array( $WC_List_Grid, 'gridlist_toggle_button' ), 30 );
```

I tried that but did not work :-(

**Comment by jameskoster** [comment]
Please post on wordpress.org. Github is not the place to get support :-)
